global using File = Project.Domain.Entities.File;
global using Type = Project.Domain.Entities.Type;
global using BuildingBlocks.CQRS;
global using Project.Application.Data;
global using ProjectEntity = Project.Domain.Entities.Projects;
global using BuildingBlocks;
global using BuildingBlocks.ApiResponse;
global using Microsoft.EntityFrameworkCore;
global using Project.Domain.Entities;
global using BuildingBlocks.Extensions;
global using Project.Domain.Enums;
global using Project.Domain.ValueObjects;
global using BuildingBlocks.Exceptions;
